### ISSUE TITLE
Only displays flickering black-n-white shapes

### ISSUE THREAD

**Issue by eikenb** [flathub/net.sourceforge.projectM#7]
This seems very similar to #4, but must have a different cause as I'm running the latest build that is using the 5.12 kde runtime (which was the fix for #4).

I'm running Debian Buster w/ Intel GPU HD5500.
Buster includes kernel 4.19 and Mesa 18.3.6.

Basically when I run it, it displays a box with black and white shapes flickering. I can him 'm' and get the menu to quit properly.

When started it displays multiple errors. I've cut-n-pasted the output below..

```
Failed to compile shader 'Vertex: v2f_c4f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to compile shader 'Fragment: v2f_c4f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: v2f_c4f_t2f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to compile shader 'Fragment: v2f_c4f_t2f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: blur1'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to compile shader 'Fragment: blur1'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: blur2'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to compile shader 'Fragment: blur2'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
No Textures Loaded from /app/share/projectM/textures
No Textures Loaded from /app/share/projectM/textures
unconnected: connecting...
connectHelper:  "alsa_output.usb-Topping_D10-00.analog-stereo.monitor"
CREATED
READY
No Textures Loaded from /app/share/projectM/textures
No Textures Loaded from /app/share/projectM/textures
No Textures Loaded from /app/share/projectM/textures
No Textures Loaded from /app/share/projectM/textures

```

**Comment by AdmiralAsshat** [comment]
Having the same problem w/ Fedora 30 and an Intel GPU.

Unfortunately, the [version on flathub](https://flathub.org/apps/details/net.sourceforge.projectM) is about a year old, and the URL for the testing branch fix given in #4 no longer works.

**Comment by TingPing** [comment]
> Unfortunately, the version on flathub is about a year old

The last stable release is a year old...

I'll update it to the latest release candidate.

>  the URL for the testing branch fix given in #4 no longer works.

Because it was merged and their problem was solved.

**Comment by eikenb** [comment]
@TingPing thanks for the update. 

Just updated my installed flatpak version to 3.1.1-rc4 but it is still having the issue. If there's anything else I can provide to help, please let me know.

**Comment by TingPing** [comment]
I think the folks over at the [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) are probably the people to start a conversation with. It is almost certainly a driver specific issue. I presume Intel specific since it works here on AMD.

Maybe attach the full output of `glxinfo` inside and outside of the sandbox (it is packaged as `org.freedesktop.GlxInfo//18.08`).

**Comment by eikenb** [comment]
Attached is that glxinfo you thought might be useful.

[glxinfo.txt](https://github.com/flathub/net.sourceforge.projectM/files/3575866/glxinfo.txt)

Do you think it is a driver issue at the kernel level or mesa?

**Comment by TingPing** [comment]
Probably Mesa since thats whats unique to Flatpak.
